name: Automatic CI

on:
  push:
    branches: [main, dev/*]
  pull_request:
    branches: [main, dev/*]

jobs:
  CheckCI:
    name: Check CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install packages
        run: npm install
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
